[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eyre = "^0.6"
color-eyre = "^0.6"
itertools = "0.10"

[dev-dependencies]
pretty_assertions = "^1"
maplit = "^1"
